const jwt = require("jsonwebtoken");
const express = require("express");

const app = express();

const value = {
    name: "Abhinav",
    accountNumber: 123567899999
}

// const token= jwt.sign(value, "secret");
const verifiedtoken = jwt.verify("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJoaW5hdiIsImFjY291bnROdW1iZXIiOjEyMzU2Nzg5OTk5OSwiaWF0IjoxNzYyNTEyNzk3fQ.7WbukASwuCAHSyfPe9VCjA0Gw9ijYhhVoyViLSXmeWg","secret");
console.log(verifiedtoken);


// this token has been generated by using this secret, and hence this token can only be verified using this secret